
(function(){
 if(localStorage.getItem('preparakey.session')!=='active'){/* keep dev friendly */}
 const DATA=window.PREPARAKEY_QUESTIONS; const PASS=window.PREPARAKEY_CONFIG.passingScore||75; const $=id=>document.getElementById(id);
 const contentVersion=window.PREPARAKEY_CONFIG.contentVersion; if(localStorage.getItem('preparakey.contentVersion')!==contentVersion){localStorage.removeItem('preparakey.history');localStorage.removeItem('preparakey.answers');localStorage.setItem('preparakey.contentVersion',contentVersion);}
 let current=null, idx=0, started=0, tick=null, visibleSessions=6;
 const store={get history(){return JSON.parse(localStorage.getItem('preparakey.history')||'[]')}, set history(v){localStorage.setItem('preparakey.history',JSON.stringify(v))}};
 function allQs(){let n=0; DATA.simulados.forEach(s=>n+=s.questions.length); DATA.areas.forEach(a=>a.sessions.forEach(s=>n+=s.questions.length)); return n;}
 function nav(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view')); $(view).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); $('pageTitle').textContent={dashboard:'Dashboard',simulados:'Simulados',areas:'Áreas',questionario:'Questionário',historico:'Histórico',configuracoes:'Configurações'}[view]||'Dashboard'; if(innerWidth<920) $('sidebar').classList.remove('open'); if(view==='dashboard') renderDashboard(); if(view==='historico') renderHistory();}
 document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.view)); $('menuBtn').onclick=()=>$('sidebar').classList.toggle('open'); $('brandHomeBtn').onclick=$('topHomeBtn').onclick=()=>nav('dashboard'); $('logoutBtn').onclick=()=>{localStorage.removeItem('preparakey.session'); location.href='index.html'}; $('resetProgressBtn').onclick=()=>{if(confirm('Limpar histórico e progresso local?')){store.history=[]; localStorage.removeItem('preparakey.answers'); renderDashboard(); renderHistory();}};
 function syncThemeButtons(){const light=document.body.classList.contains('light'); $('lightThemeBtn')?.classList.toggle('active-theme',light); $('darkThemeBtn')?.classList.toggle('active-theme',!light);} $('darkThemeBtn').onclick=()=>{document.body.classList.remove('light'); localStorage.setItem('preparakey.theme','dark'); syncThemeButtons(); renderDashboard();}; $('lightThemeBtn').onclick=()=>{document.body.classList.add('light'); localStorage.setItem('preparakey.theme','light'); syncThemeButtons(); renderDashboard();}; if(localStorage.getItem('preparakey.theme')==='light') document.body.classList.add('light'); syncThemeButtons();
 function renderCards(){const exam=$('examGrid'); exam.innerHTML=''; const examDescription=document.querySelector('#simulados .section-head .muted'); if(examDescription&&!DATA.simulados.length)examDescription.textContent='Nenhum simulado pertence à nova base de perguntas.'; DATA.simulados.forEach(s=>{let d=document.createElement('article');d.className='study-card '+(!s.available?'disabled':'');d.innerHTML=`<h3>${s.title}</h3><p class="meta">${s.available?s.questions.length+' questões':'Em breve'}</p><button class="${s.available?'primary-btn':'secondary-btn'}" ${!s.available?'disabled':''}>${s.available?'Iniciar':'Em breve'}</button>`; if(s.available)d.querySelector('button').onclick=()=>startQuiz(s.title,s.questions,'simulado'); exam.appendChild(d)});
 renderSessions();}
 function renderSessions(){const grid=$('areaGrid'); grid.innerHTML=''; const sessions=DATA.areas[0].sessions.slice(0,visibleSessions); sessions.forEach(s=>{let d=document.createElement('article'); d.className='study-card '+(!s.available?'disabled':''); d.innerHTML=`<h3>Sessão ${s.number}</h3><p class="meta">${s.available?s.questions.length+' questões':'Em breve'} ${s.note?'• '+s.note:''}</p><button class="${s.available?'primary-btn':'secondary-btn'}" ${!s.available?'disabled':''}>${s.available?'Iniciar sessão':'Em breve'}</button>`; if(s.available)d.querySelector('button').onclick=()=>startQuiz(`Fundamentos — Sessão ${s.number}`,s.questions,'sessao'); grid.appendChild(d)}); $('loadMoreSessionsBtn').style.display=visibleSessions>=DATA.areas[0].sessions.length?'none':'inline-flex';}
 $('loadMoreSessionsBtn').onclick=()=>{visibleSessions+=6; renderSessions();};
 function startQuiz(title,questions,mode){current={title,questions,mode,answers:{},verified:{},startedAt:Date.now()}; idx=0; started=Date.now(); if(tick)clearInterval(tick); tick=setInterval(updateTimer,1000); $('finishBtn').disabled=false; nav('questionario'); renderQuestion();}
 function updateTimer(){let s=Math.floor((Date.now()-started)/1000); $('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
 function qRequired(q){return q.required||((q.answer||[]).length>1?(q.answer||[]).length:1)}
 function renderQuestion(){const q=current.questions[idx]; $('quizTitle').textContent=current.title; $('quizSubtitle').textContent=`Questão ${idx+1}/${current.questions.length}`; $('prevBtn').disabled=idx===0; $('finishBtn').disabled=false; const req=qRequired(q); const raw=current.answers[q.id]; const sel=Array.isArray(raw)?raw:[]; const isVer=current.verified[q.id]; const isMatching=q.type==='matching'; const ready=isMatching?Object.keys(current.answers[q.id]||{}).length===q.pairs.length:sel.length===req; $('verifyBtn').disabled=!ready || isVer; $('verifyBtn').classList.toggle('ready-pulse',ready&&!isVer); $('nextBtn').disabled=!isVer; document.querySelector('.quiz-toolbar')?.classList.toggle('ready-to-verify',ready&&!isVer); const cont=$('quizContainer'); cont.className='quiz-container'; let typeLabel=q.type==='multiple'?`Escolha ${req}`:q.type==='matching'?'Associação':'Única resposta'; let html=`<div class="q-meta"><span class="tag">Questão ${idx+1}/${current.questions.length}</span><span class="tag">${q.domain||'Processo'}</span><span class="tag">${typeLabel}</span></div><div class="question-text">${escape(q.question).replace(/\n/g,'<br>')}</div>`;
 if(q.type==='matching') html+=renderMatching(q); else { const locked=q.type==='multiple' && sel.length>=req; html+=`<div class="selection-status ${ready?'ready':''}"><strong>${ready?'Pronto para verificar':'Selecione para continuar'}</strong><span>${sel.length}/${req} alternativa${req>1?'s':''} selecionada${req>1?'s':''}. ${req>1?'O limite é exatamente '+req+' alternativas.':'Ao selecionar, use Verificar para liberar Avançar.'}</span></div><div class="options">${q.options.map(o=>`<button class="option ${sel.includes(o.id)?'selected':''} ${locked&&!sel.includes(o.id)&&!isVer?'disabled-option':''} ${isVer?markClass(q,o.id):''}" data-opt="${o.id}" ${locked&&!sel.includes(o.id)&&!isVer?'aria-disabled="true"':''}><span class="letter">${o.id}</span><span>${escape(o.text)}</span></button>`).join('')}</div>`; }
 if(isVer) html+=feedbackHtml(q,sel); cont.innerHTML=html; cont.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>selectOption(q,btn.dataset.opt)); if(q.type==='matching'){cont.querySelectorAll('select').forEach(selEl=>selEl.onchange=()=>selectMatching(q));}
 } function renderMatching(q){const rights=[...q.pairs.map(p=>p.right)].sort(()=>Math.random()-.5); const saved=current.answers[q.id]||{}; return `<div class="matching-grid">${q.pairs.map(p=>`<div class="match-row"><strong>${escape(p.left)}</strong><select data-left="${escape(p.left)}"><option value="">Selecione...</option>${rights.map(r=>`<option ${saved[p.left]===r?'selected':''} value="${escape(r)}">${escape(r)}</option>`).join('')}</select></div>`).join('')}</div>`;}
 function selectMatching(q){let obj={}; document.querySelectorAll('[data-left]').forEach(s=>{if(s.value)obj[s.dataset.left]=s.value}); current.answers[q.id]=obj; current.verified[q.id]=false; const ok=Object.keys(obj).length===q.pairs.length; $('verifyBtn').disabled=!ok; $('verifyBtn').classList.toggle('ready-pulse',ok); $('nextBtn').disabled=true; document.querySelector('.quiz-toolbar')?.classList.toggle('ready-to-verify',ok); if(ok) setTimeout(()=>$('verifyBtn').scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'}),80);} function selectOption(q,opt){let arr=current.answers[q.id]||[]; const req=qRequired(q); if(q.type==='multiple'){ if(arr.includes(opt)) arr=arr.filter(x=>x!==opt); else if(arr.length<req) arr.push(opt); else return; } else arr=[opt]; current.answers[q.id]=arr; current.verified[q.id]=false; renderQuestion(); setTimeout(()=>{const reqNow=qRequired(q); const ready=(current.answers[q.id]||[]).length===reqNow; $('verifyBtn').disabled=!ready; $('verifyBtn').classList.toggle('ready-pulse',ready); $('nextBtn').disabled=true; document.querySelector('.quiz-toolbar')?.classList.toggle('ready-to-verify',ready); if(ready) $('verifyBtn').scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});},0);} $('verifyBtn').onclick=()=>{const q=current.questions[idx]; current.verified[q.id]=true; renderQuestion(); $('nextBtn').disabled=false; $('nextBtn').scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});}; $('prevBtn').onclick=()=>{if(idx>0){idx--; renderQuestion();}}; $('nextBtn').onclick=()=>{if(!current.verified[current.questions[idx].id])return; if(idx<current.questions.length-1){idx++; renderQuestion();} else finishQuiz();}; $('finishBtn').onclick=()=>finishQuiz();
 function isCorrect(q,ans){if(q.type==='matching'){return q.pairs.every(p=>ans&&ans[p.left]===p.right)} const a=(q.answer||[]).slice().sort().join(','); const b=(ans||[]).slice().sort().join(','); return a===b;}
 function markClass(q,opt){const ans=current.answers[q.id]||[]; const corr=(q.answer||[]).includes(opt); if(corr)return 'correct'; if(ans.includes(opt)&&!corr)return 'wrong'; return '';}
 function feedbackHtml(q,sel){const ok=isCorrect(q,q.type==='matching'?current.answers[q.id]:sel); return `<div class="feedback ${ok?'is-correct':'is-wrong'}"><strong>${ok?'Correto':'Incorreto'}</strong><p>${escape(q.explanation||'')}</p><p><b>Resposta:</b> ${q.type==='matching'?'Associações corretas':(q.answer||[]).join(', ')}</p><p class="muted"><b>Referência:</b> ${escape(q.reference||'PMBOK 7 / Guia Ágil')}</p></div>`;} function finishQuiz(){if(!current)return; const unanswered=current.questions.find(q=>!current.verified[q.id]); if(unanswered&&!confirm('Há questões não verificadas. Finalizar mesmo assim?'))return; let correct=0; const detail=current.questions.map((q,i)=>{const ans=current.answers[q.id]||(q.type==='matching'?{}:[]); const ok=isCorrect(q,ans); if(ok)correct++; return {number:i+1,question:q.question,answer:ans,correctAnswer:q.type==='matching'?q.pairs:q.answer,correct:ok,explanation:q.explanation,reference:q.reference};}); const score=Math.round(correct/current.questions.length*100); const rec={id:'h'+Date.now(),title:current.title,date:new Date().toLocaleString('pt-BR'),total:current.questions.length,correct,wrong:current.questions.length-correct,score,approved:score>=PASS,detail}; const hist=store.history; hist.unshift(rec); store.history=hist; if(tick)clearInterval(tick); alert(`${score>=PASS?'Aprovado':'Reprovado'} — ${score}%`); current=null; nav('historico');}
 function renderDashboard(){const hist=store.history; $('totalQuestions').textContent=allQs(); const avg=hist.length?Math.round(hist.reduce((a,b)=>a+b.score,0)/hist.length):0; const last=hist[0]; $('avgScore').textContent=avg+'%'; $('lastScore').textContent=last?last.score+'%':'0%'; $('readiness').textContent=avg+'%'; $('readinessStatus').textContent=avg>=75?'Pronto para prova':avg>=65?'Em progresso':'Necessita reforço'; $('readinessInsight').textContent=hist.length?'Baseado no histórico local.':'Finalize um simulado ou sessão para gerar diagnóstico.'; $('lastDecision').textContent=last?(last.approved?'Aprovado':'Reprovado'):'Sem avaliação'; $('approvalPill').textContent=avg>=75?'Pronto':avg>=65?'Em progresso':'Aguardando evolução'; drawDonut(avg); drawBars(hist); renderInsights(avg,hist);}
 function drawDonut(score){const r=82,c=2*Math.PI*r,p=score/100*c; $('pieChart').innerHTML=`<svg viewBox="0 0 260 260" width="100%" height="260"><circle cx="130" cy="130" r="82" fill="none" stroke="#22314c" stroke-width="30"/><circle cx="130" cy="130" r="82" fill="none" stroke="#22c55e" stroke-width="30" stroke-linecap="round" stroke-dasharray="${p} ${c-p}" transform="rotate(-90 130 130)"/><text x="130" y="125" text-anchor="middle" font-size="44" font-weight="900" fill="currentColor">${score}%</text><text x="130" y="158" text-anchor="middle" font-size="14" fill="currentColor">readiness</text></svg>`;}
 function drawBars(hist){
 const vals=[['Pessoas',hist[0]?.score||0],['Processo',Math.max(0,(hist[0]?.score||0)-4)],['Negócio',Math.min(100,(hist[0]?.score||0)+3)]]; $('barChart').innerHTML='<div class="bars">'+vals.map(v=>`<div><b>${v[0]}</b><span>${v[1]}%</span><div style="height:12px;background:#22314c;border-radius:999px"><i style="display:block;width:${v[1]}%;height:12px;background:linear-gradient(90deg,#2563eb,#15b8dc);border-radius:999px"></i></div></div>`).join('')+'</div>';}
 function renderInsights(avg,hist){$('insightList').innerHTML=hist.length?`<div class="review-q"><b>${avg>=75?'Pronto para prova':'Plano de reforço'}</b><p>${avg>=75?'Mantenha revisão por erros e simulados completos.':'Priorize revisar questões erradas e refazer sessões com menor desempenho.'}</p></div>`:'<p class="muted">Sem dados ainda.</p>';}
 function renderHistory(){const h=store.history; const list=$('historyList'); if(!h.length){list.innerHTML='<p class="muted">Nenhum resultado salvo.</p>'; $('historyDetail').innerHTML=''; return;} list.innerHTML=h.map(r=>`<article class="history-item"><div><a href="#" data-hid="${r.id}"><strong>${r.title}</strong></a><p class="muted">${r.date} • ${r.correct}/${r.total} • ${r.score}% • ${r.approved?'Aprovado':'Reprovado'}</p></div><button class="secondary-btn" data-more="${r.id}">Ver mais</button></article>`).join(''); list.querySelectorAll('[data-hid],[data-more]').forEach(el=>el.onclick=(e)=>{e.preventDefault(); showHistory(el.dataset.hid||el.dataset.more)});}
 function showHistory(id){const r=store.history.find(x=>x.id===id); if(!r)return; $('historyDetail').innerHTML=`<article class="panel"><h2>${r.title}</h2><p>${r.score}% • ${r.correct} acertos • ${r.wrong} erros</p>${r.detail.map(d=>`<div class="review-q"><b>Questão ${d.number} — ${d.correct?'Correta':'Errada'}</b><p>${escape(d.question)}</p><p class="muted"><b>Sua resposta:</b> ${typeof d.answer==='object'?escape(JSON.stringify(d.answer)):escape(String(d.answer))}</p><p class="muted"><b>Gabarito:</b> ${escape(JSON.stringify(d.correctAnswer))}</p></div>`).join('')}</article>`;}
 function escape(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
 renderCards(); renderDashboard();
})();
